/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Which AI features are on.
         * @description Called once per session by the frontend. A 404 or a network failure means no AI element renders and every screen is as it is without AI.
         */
        get: operations["getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reflections/{reflection_id}/entries/{entry_id}/coach": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Questions about a draft narrative, for the student writing it.
         * @description One to three open questions about this competency's narrative. Never words for the narrative and never a level: the coach is not told the self-score, and questions that mention a level, a score or a number on the scale are dropped. Only the student who owns the reflection, only on a draft, and only once the narrative has 15 words. The path goes through the reflection because the diary has no GET /entries/{id}.
         */
        post: operations["askCoach"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reflections/{reflection_id}/entries/{entry_id}/related": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The student's own earlier entries that read most like this one.
         * @description Up to three of the student's own entries from their other reflections, best first, ranked by meaning within the reflections the diary returned for their token. No Claude call. Only the student who owns the reflection. An empty narrative, or nothing earlier, is an empty list.
         */
        get: operations["getRelated"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CoachQuestions: {
            questions: string[];
        };
        RelatedEntries: {
            entries: {
                /** Format: uuid */
                reflection_id: string;
                /** Format: uuid */
                entry_id: string;
                sprint_ordinal: number | null;
                competency_name: string;
                /** @description The narrative's first line, cut at a word. */
                excerpt: string;
            }[];
        };
        Status: {
            features: ("coach" | "related" | "calibration" | "search" | "themes")[];
        };
        Error: {
            error: {
                /** @enum {string} */
                code: "UNAUTHENTICATED" | "ROLE_FORBIDDEN" | "NOT_FOUND" | "VALIDATION_FAILED" | "AI_DISABLED" | "AI_RATE_LIMITED" | "AI_UNAVAILABLE";
                message: string;
                /** @description AI_RATE_LIMITED carries retry_after, in seconds. AI_UNAVAILABLE carries reason, one of timeout, upstream, refusal, invalid_reply, daily_cap. */
                details: Record<string, never>;
            };
        };
    };
    responses: {
        /** @description The diary's error envelope. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        ReflectionId: string;
        EntryId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description On, with the features this deployment serves. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    askCoach: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reflection_id: components["parameters"]["ReflectionId"];
                entry_id: components["parameters"]["EntryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The questions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoachQuestions"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            429: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    getRelated: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reflection_id: components["parameters"]["ReflectionId"];
                entry_id: components["parameters"]["EntryId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The related entries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelatedEntries"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            429: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
}
