/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The caller and their role on each gig
         * @description Drives role-aware navigation. Roles are resolved server-side from gig_participants and are never accepted from the client.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gigs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gigs the caller participates in, in any role */
        get: operations["listGigs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gigs/{gig_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One gig, with its participants */
        get: operations["getGig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/frameworks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Available rubrics */
        get: operations["listFrameworks"];
        put?: never;
        /**
         * Copy a base template, supervisor only
         * @description Copy-then-edit is the only editing model. There is no way to create a framework from nothing, and no way to change one that a reflection already references, because doing either would silently change what past students were scored against.
         */
        post: operations["copyFramework"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/frameworks/{framework_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One rubric with its competencies and level descriptors
         * @description Drives the entry stepper, the radar axes and the framework editor. scale comes from the v_framework_scale view rather than from a stored column, because a SFIA skill is valid over only part of the seven-point scale.
         */
        get: operations["getFramework"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename or adjust policy, on your own unused copy */
        patch: operations["updateFramework"];
        trace?: never;
    };
    "/competencies/{competency_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Rename a competency on your own unused copy
         * @description Renaming and rewording only. Adding or removing competencies, and changing how many levels one has, are out of scope: a rubric with a different shape is a different rubric.
         */
        patch: operations["updateCompetency"];
        trace?: never;
    };
    "/levels/{level_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Reword a level descriptor on your own unused copy
         * @description The descriptor is what a student reads when deciding what to score themselves, so this is the edit most likely to matter.
         */
        patch: operations["updateLevel"];
        trace?: never;
    };
    "/framework-assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign a rubric to a gig, supervisor or employer */
        post: operations["assignFramework"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reflections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reflections the caller may see, newest first
         * @description A student sees their own. An assessor, supervisor or employer sees every reflection on the gigs they are on.
         */
        get: operations["listReflections"];
        put?: never;
        /**
         * Start a reflection on a gig or a sprint
         * @description One of gig_id or sprint_id is required; a sprint knows its gig, so sending both and disagreeing is refused rather than guessed at. One entry is created eagerly per competency, so the stepper can say "3 of 6" before anything is written.
         */
        post: operations["createReflection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reflections/{reflection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The screen payload, for the student and the assessor alike */
        get: operations["getReflection"];
        put?: never;
        post?: never;
        /**
         * Discard a draft, owner only
         * @description Draft only. A submitted or assessed record cannot be deleted through the API at all, which is part of the ownership promise.
         */
        delete: operations["deleteReflection"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reflections/{reflection_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Hand it in, once the gate passes
         * @description Every entry needs a narrative and a self-score, and evidence too if the rubric requires it. The gate refuses on the first rule that fails and names the offending entries in details.entry_ids, because the stepper sends the student straight to them.
         */
        post: operations["submitReflection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reflections/{reflection_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The history, newest first
         * @description Append-only. Notifications are derived from this rather than stored separately.
         */
        get: operations["getReflectionEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Autosave a narrative, owner and draft only */
        patch: operations["updateEntry"];
        trace?: never;
    };
    "/entries/{entry_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Attach a link or a file to an entry
         * @description A link as JSON, a file as multipart. Type and size are checked against the rubric's own policy rather than a global setting.
         */
        post: operations["addEvidence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evidence/{evidence_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove evidence, owner and draft only */
        delete: operations["deleteEvidence"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/{entry_id}/scores/self": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * The student's own score, upserted
         * @description PUT, because changing your mind before submitting replaces the score rather than adding a second one. The level must belong to this entry's competency; the database cannot express that, so the API checks it.
         */
        put: operations["setSelfScore"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries/{entry_id}/scores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * A counter-score from an assessor, supervisor or employer
         * @description The reflection must be submitted: a draft is too early and an assessed one is too late, because the most recent counter-score is the one that counts and a late one would move a radar the record was already closed on. A comment is required when the score is below the student's own, and whenever the rubric asks for one. One score per scorer per entry: there is no re-scoring, and a repeat is a conflict. When the last entry is scored the reflection flips to assessed, which closes it for every other scorer.
         */
        post: operations["addCounterScore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Submitted reflections awaiting the caller's own score
         * @description Per caller, not per gig. A gig can have both an assessor and a supervisor, and a reflection one of them has scored is still work for the other, until the last entry completes it for everybody.
         */
        get: operations["getReviewQueue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/radar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Self against counter, per competency
         * @description Scope mirrors the UI. A sprint gives that sprint's comparison, a gig the latest within it, neither the latest across the record. Unscoped needs a framework chosen for it, because a student on two gigs can be scored against two rubrics whose codes do not overlap; the most recent reflection decides and the response says which.
         */
        get: operations["getRadar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The same two numbers along the sprints of one gig */
        get: operations["getProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/calibration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Self minus counter, per competency
         * @description A positive gap means the student rated themselves higher than the person assessing them did. Null until both sides have scored.
         */
        get: operations["getCalibration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Competencies the caller has never been scored on
         * @description Scored, not evidenced. Evidence is optional per rubric, so requiring it would report gaps that are not gaps. Scoped to rubrics the caller studies under, so an assessor gets an empty list.
         */
        get: operations["getCoverage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Your own export history */
        get: operations["listExports"];
        put?: never;
        /**
         * Ask for the record as a file
         * @description Returns 202 with whatever the row says. On a synchronous queue the job has already run and it reads complete; on a worker it reads pending. Poll until status is complete or failed.
         */
        post: operations["requestExport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exports/{export_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll one export */
        get: operations["getExport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exports/{export_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The file itself, owner only
         * @description Served through the API rather than as a link, so the policy runs on every fetch. Export is "own" for every role, so not even a supervisor on the gig can read one.
         */
        get: operations["downloadExport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description The single envelope for every non-2xx response. No endpoint returns any other error shape. */
        Error: {
            error: {
                /**
                 * @description The full enumeration for the product, not only the codes these five endpoints can raise. A response carrying a code outside this list is a bug in the endpoint.
                 * @enum {string}
                 */
                code: "VALIDATION_FAILED" | "CONTEXT_REQUIRED" | "DUPLICATE_REFLECTION" | "DUPLICATE_ASSIGNMENT" | "NOT_DRAFT" | "NOT_SUBMITTED" | "COMMENT_REQUIRED" | "LEVEL_NOT_IN_COMPETENCY" | "EVIDENCE_REQUIRED" | "NARRATIVE_REQUIRED" | "SELF_SCORE_MISSING" | "FILE_TYPE_NOT_ACCEPTED" | "FILE_TOO_LARGE" | "FRAMEWORK_NOT_ASSIGNED" | "FRAMEWORK_IN_USE" | "ALREADY_SCORED" | "ROLE_FORBIDDEN" | "UNAUTHENTICATED" | "NOT_FOUND";
                /** @description Human readable. Never switch on this. */
                message: string;
                details: {
                    [key: string]: unknown;
                };
            };
        };
        /** @enum {string} */
        Role: "student" | "assessor" | "supervisor" | "employer";
        /**
         * @description Which role gave the counter-score. The class is always "counter"; this names who it was, because the radar draws one opposing polygon and the legend still has to be honest about whose it is.
         * @enum {string|null}
         */
        CounterRole: "assessor" | "supervisor" | "employer" | null;
        /**
         * @description Forward only. Draft is the only editable state, and a submitted record cannot be deleted through the API at all.
         * @enum {string}
         */
        ReflectionStatus: "draft" | "submitted" | "assessed";
        Person: {
            /** Format: uuid */
            id: string;
            display_name: string;
        };
        CompetencySummary: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            framework_id: string;
            code: string;
            name: string;
            short_label: string | null;
            category: string | null;
            position: number;
        };
        Evidence: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            reflection_entry_id: string;
            /** @enum {string} */
            kind: "file" | "link" | "image";
            label: string;
            /** @description A URL for a link, a storage path for a file. Files are fetched through the API, never from this path directly. */
            uri: string;
            size_bytes: number | null;
            /** Format: date-time */
            uploaded_at: string;
        };
        Score: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            reflection_entry_id: string;
            scorer_role: components["schemas"]["Role"];
            /**
             * @description An assessor, a supervisor and an employer all counter-score, so the opposing value is a class rather than a role.
             * @enum {string}
             */
            scorer_class: "self" | "counter";
            /** Format: uuid */
            level_id: string;
            level_value: number;
            comment: string | null;
            /** Format: date-time */
            scored_at: string;
        };
        ReflectionSummary: {
            /** Format: uuid */
            id: string;
            status: components["schemas"]["ReflectionStatus"];
            /** Format: uuid */
            gig_id: string | null;
            /** Format: uuid */
            sprint_id: string | null;
            sprint_ordinal?: number | null;
            /** Format: uuid */
            framework_id: string;
            /** @description Snapshotted when the reflection was created, not read from the framework now. The framework is frozen from that moment, so the pair identifies exactly what was scored. */
            framework_version: string;
            /** Format: date-time */
            submitted_at: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ReflectionEntry: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            competency_id: string;
            competency_code: string;
            competency_name: string;
            short_label: string | null;
            position: number;
            narrative: string | null;
            evidence: components["schemas"]["Evidence"][];
            /** @description Oldest first, so the self-score precedes the counter-scores. */
            scores: (components["schemas"]["Score"] & {
                scorer?: components["schemas"]["Person"];
            })[];
        };
        ReflectionDetail: components["schemas"]["ReflectionSummary"] & {
            owner: components["schemas"]["Person"];
            /** @description In rubric order, one per competency, created eagerly. */
            entries: components["schemas"]["ReflectionEntry"][];
        };
        Export: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            format: "json" | "pdf";
            /**
             * @description Stored, not derived from completed_at. A failed job has no completion time and no file, so without this the poll loop could never tell failure from slowness.
             * @enum {string}
             */
            status: "pending" | "complete" | "failed";
            /**
             * Format: uuid
             * @description Null means the whole record.
             */
            reflection_id: string | null;
            /** @description Counts of what went into the file. Null until it is built. */
            summary: {
                [key: string]: unknown;
            } | null;
            /** Format: date-time */
            requested_at: string;
            /** Format: date-time */
            completed_at: string | null;
            uri: string | null;
        };
        Me: {
            /** Format: uuid */
            id: string;
            display_name: string;
            participations: {
                /** Format: uuid */
                gig_id: string;
                gig_title: string;
                role: components["schemas"]["Role"];
            }[];
        };
        Sprint: {
            /** Format: uuid */
            id: string;
            ordinal: number;
            /** Format: date */
            opens_on: string | null;
            /** Format: date */
            due_on: string | null;
        };
        /** @description The framework assigned to the gig, null until one is. */
        GigFramework: {
            /** Format: uuid */
            id: string;
            fw_key: string;
            name: string;
            version: string;
        } | null;
        /** @description Counts of the reflections on this gig that the caller is allowed to see. A student sees their own; an assessor, supervisor or employer sees every reflection on the gig. */
        ReflectionCounts: {
            draft: number;
            submitted: number;
            assessed: number;
        };
        Gig: {
            /** Format: uuid */
            id: string;
            title: string;
            org_name: string | null;
            /** Format: date */
            starts_on: string | null;
            /** Format: date */
            ends_on: string | null;
            my_role: components["schemas"]["Role"];
            sprints: components["schemas"]["Sprint"][];
            framework: components["schemas"]["GigFramework"];
            reflection_summary: components["schemas"]["ReflectionCounts"];
        };
        GigDetail: components["schemas"]["Gig"] & {
            participants: {
                /** Format: uuid */
                id: string;
                display_name: string;
                role: components["schemas"]["Role"];
            }[];
        };
        Framework: {
            /** Format: uuid */
            id: string;
            fw_key: string;
            version: string;
            name: string;
            is_active: boolean;
            /**
             * Format: uuid
             * @description Null for a seeded base template, set for someone's copy.
             */
            created_by: string | null;
            /** @description True when at least one reflection references it, which makes it permanently read-only. Derived, never stored. */
            in_use: boolean;
        };
        Level: {
            /** Format: uuid */
            id: string;
            level_value: number;
            descriptor: string;
        };
        Competency: {
            /** Format: uuid */
            id: string;
            code: string;
            name: string;
            /** @description Radar axis label, kept short enough to fit. */
            short_label: string | null;
            /** @description SFIA grouping. Null for La Trobe. */
            category: string | null;
            position: number;
            levels: components["schemas"]["Level"][];
        };
        /** @description Read from v_framework_scale, not aggregated in PHP. */
        Scale: {
            min: number;
            max: number;
        };
        FrameworkDetail: {
            /** Format: uuid */
            id: string;
            fw_key: string;
            version: string;
            name: string;
            /** Format: uuid */
            created_by: string | null;
            in_use: boolean;
            comment_required: boolean;
            evidence_required: boolean;
            accepted_file_types: string[] | null;
            max_file_bytes: number;
            scale: components["schemas"]["Scale"];
            competencies: components["schemas"]["Competency"][];
        };
    };
    responses: {
        /** @description Missing or invalid bearer token */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "UNAUTHENTICATED",
                 *         "message": "A valid bearer token is required.",
                 *         "details": {}
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The payload or a business rule refused it */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The caller can see the resource but their role does not permit this action. Distinct from 404, which means they should not know it exists. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "ROLE_FORBIDDEN",
                 *         "message": "Your role on this gig does not permit that.",
                 *         "details": {}
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description A reflection references this framework, so it is permanently read-only. Copy it and edit the copy. */
        FrameworkInUse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "FRAMEWORK_IN_USE",
                 *         "message": "This framework has been used to score a reflection and can no longer be changed.",
                 *         "details": {
                 *           "framework_id": "aaaa1111-0000-4aaa-8aaa-aaaaaaaaaaaa"
                 *         }
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Done. No body. */
        NoContent: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description No such resource, or it exists and is not the caller's. The two are deliberately indistinguishable. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "NOT_FOUND",
                 *         "message": "No such resource, or it is not yours.",
                 *         "details": {}
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        GigId: string;
        FrameworkId: string;
        ReflectionId: string;
        EntryId: string;
        ExportId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "6f1c2b6e-0f5a-4a3f-9d4a-3a1b7c9e2d10",
                     *       "display_name": "Jane N",
                     *       "participations": [
                     *         {
                     *           "gig_id": "b2c3d4e5-1111-4a2b-9c3d-4e5f60718293",
                     *           "gig_title": "Develop AI use cases",
                     *           "role": "student"
                     *         },
                     *         {
                     *           "gig_id": "c3d4e5f6-2222-4b3c-8d4e-5f6071829304",
                     *           "gig_title": "Data migration audit",
                     *           "role": "student"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    listGigs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's gigs, empty if they are on none */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "id": "b2c3d4e5-1111-4a2b-9c3d-4e5f60718293",
                     *         "title": "Develop AI use cases",
                     *         "org_name": "Alumable",
                     *         "starts_on": "2026-08-03",
                     *         "ends_on": "2026-10-26",
                     *         "my_role": "student",
                     *         "sprints": [
                     *           {
                     *             "id": "11111111-aaaa-4111-8111-111111111111",
                     *             "ordinal": 1,
                     *             "opens_on": "2026-08-03",
                     *             "due_on": "2026-08-16"
                     *           },
                     *           {
                     *             "id": "22222222-aaaa-4222-8222-222222222222",
                     *             "ordinal": 2,
                     *             "opens_on": "2026-08-17",
                     *             "due_on": "2026-08-30"
                     *           }
                     *         ],
                     *         "framework": {
                     *           "id": "aaaa1111-0000-4aaa-8aaa-aaaaaaaaaaaa",
                     *           "fw_key": "latrobe6",
                     *           "name": "La Trobe six-competency",
                     *           "version": "v1"
                     *         },
                     *         "reflection_summary": {
                     *           "draft": 1,
                     *           "submitted": 0,
                     *           "assessed": 1
                     *         }
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["Gig"][];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    getGig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gig_id: components["parameters"]["GigId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The gig */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GigDetail"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    listFrameworks: {
        parameters: {
            query?: {
                /** @description Limit to frameworks with is_active true. */
                active?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Frameworks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "id": "aaaa1111-0000-4aaa-8aaa-aaaaaaaaaaaa",
                     *         "fw_key": "latrobe6",
                     *         "version": "v1",
                     *         "name": "La Trobe six-competency",
                     *         "is_active": true,
                     *         "created_by": null,
                     *         "in_use": true
                     *       },
                     *       {
                     *         "id": "bbbb2222-0000-4bbb-8bbb-bbbbbbbbbbbb",
                     *         "fw_key": "sfia9",
                     *         "version": "9.0",
                     *         "name": "SFIA 9",
                     *         "is_active": true,
                     *         "created_by": null,
                     *         "in_use": false
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["Framework"][];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    copyFramework: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    based_on_framework_id: string;
                    name: string;
                };
            };
        };
        responses: {
            /** @description The new copy, nested in full */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameworkDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    getFramework: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                framework_id: components["parameters"]["FrameworkId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The framework */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "aaaa1111-0000-4aaa-8aaa-aaaaaaaaaaaa",
                     *       "fw_key": "latrobe6",
                     *       "version": "v1",
                     *       "name": "La Trobe six-competency",
                     *       "created_by": null,
                     *       "in_use": true,
                     *       "comment_required": true,
                     *       "evidence_required": false,
                     *       "accepted_file_types": [
                     *         "pdf",
                     *         "png",
                     *         "jpg"
                     *       ],
                     *       "max_file_bytes": 10485760,
                     *       "scale": {
                     *         "min": 1,
                     *         "max": 4
                     *       },
                     *       "competencies": [
                     *         {
                     *           "id": "cccc3333-0000-4ccc-8ccc-cccccccccccc",
                     *           "code": "collaboration",
                     *           "name": "Collaboration",
                     *           "short_label": "Collab.",
                     *           "category": null,
                     *           "position": 3,
                     *           "levels": [
                     *             {
                     *               "id": "dddd4444-0000-4ddd-8ddd-dddddddddddd",
                     *               "level_value": 1,
                     *               "descriptor": "Emerging, acts when prompted."
                     *             },
                     *             {
                     *               "id": "eeee5555-0000-4eee-8eee-eeeeeeeeeeee",
                     *               "level_value": 4,
                     *               "descriptor": "Advanced, shapes the work and lifts others."
                     *             }
                     *           ]
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["FrameworkDetail"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    updateFramework: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                framework_id: components["parameters"]["FrameworkId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    comment_required?: boolean;
                    evidence_required?: boolean;
                    accepted_file_types?: string[] | null;
                    max_file_bytes?: number;
                };
            };
        };
        responses: {
            /** @description The updated framework */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameworkDetail"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            /** @description Not your copy. A seeded base template belongs to nobody and can never be edited; copy it instead. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["FrameworkInUse"];
        };
    };
    updateCompetency: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                competency_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name?: string;
                    short_label?: string | null;
                };
            };
        };
        responses: {
            /** @description The updated competency */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetencySummary"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["FrameworkInUse"];
        };
    };
    updateLevel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                level_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    descriptor: string;
                };
            };
        };
        responses: {
            /** @description The updated level */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Level"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["FrameworkInUse"];
        };
    };
    assignFramework: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    framework_id: string;
                    /** Format: uuid */
                    gig_id: string;
                };
            };
        };
        responses: {
            /** @description The assignment */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        /** Format: uuid */
                        gig_id: string;
                        /** Format: uuid */
                        framework_id: string;
                        /** Format: uuid */
                        assigned_by: string | null;
                        /** Format: date-time */
                        assigned_at: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description DUPLICATE_ASSIGNMENT. A gig is scored against one rubric, so this covers both assigning the same one twice and assigning a second, different one. details.framework_id names the rubric the gig already has. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "DUPLICATE_ASSIGNMENT",
                     *         "message": "This gig already has a rubric, and a gig is scored against one.",
                     *         "details": {
                     *           "framework_id": "aaaa1111-0000-4aaa-8aaa-aaaaaaaaaaaa"
                     *         }
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listReflections: {
        parameters: {
            query?: {
                gig_id?: string;
                sprint_id?: string;
                status?: components["schemas"]["ReflectionStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reflections */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReflectionSummary"][];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    createReflection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    gig_id?: string | null;
                    /** Format: uuid */
                    sprint_id?: string | null;
                };
            };
        };
        responses: {
            /** @description The new draft, nested in full */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReflectionDetail"];
                };
            };
            /** @description CONTEXT_REQUIRED when neither id is given or they disagree. FRAMEWORK_NOT_ASSIGNED when the gig has no rubric yet. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description A reflection already exists for that context */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "DUPLICATE_REFLECTION",
                     *         "message": "A reflection already exists for that context.",
                     *         "details": {}
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getReflection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reflection_id: components["parameters"]["ReflectionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The reflection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReflectionDetail"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteReflection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reflection_id: components["parameters"]["ReflectionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Not a draft */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    submitReflection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reflection_id: components["parameters"]["ReflectionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Submitted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReflectionDetail"];
                };
            };
            /** @description NARRATIVE_REQUIRED, SELF_SCORE_MISSING or EVIDENCE_REQUIRED, each with details.entry_ids. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "NARRATIVE_REQUIRED",
                     *         "message": "Every competency needs something written before you can submit.",
                     *         "details": {
                     *           "entry_ids": [
                     *             "11111111-aaaa-4111-8111-111111111111"
                     *           ]
                     *         }
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Already submitted */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getReflectionEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reflection_id: components["parameters"]["ReflectionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        /** @example reflection_submitted */
                        event_type: string;
                        actor_display_name: string | null;
                        /** Format: date-time */
                        occurred_at: string;
                        metadata: {
                            [key: string]: unknown;
                        };
                    }[];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    updateEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: components["parameters"]["EntryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    narrative: string | null;
                };
            };
        };
        responses: {
            /** @description The updated entry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        /** Format: uuid */
                        reflection_id: string;
                        /** Format: uuid */
                        competency_id: string;
                        narrative: string | null;
                        /** Format: date-time */
                        updated_at: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Not a draft */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    addEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: components["parameters"]["EntryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    kind: "link";
                    label: string;
                    /** Format: uri */
                    uri: string;
                };
                "multipart/form-data": {
                    label: string;
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description The attached evidence */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Evidence"];
                };
            };
            /** @description FILE_TYPE_NOT_ACCEPTED or FILE_TOO_LARGE, per the rubric */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Not a draft */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evidence_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContent"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Not a draft */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    setSelfScore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: components["parameters"]["EntryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    level_id: string;
                };
            };
        };
        responses: {
            /** @description The score */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Score"];
                };
            };
            /** @description LEVEL_NOT_IN_COMPETENCY */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Not a draft */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    addCounterScore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: components["parameters"]["EntryId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    level_id: string;
                    comment?: string | null;
                };
            };
        };
        responses: {
            /** @description The score, and whether it completed the reflection */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Score"] & {
                        reflection_status: components["schemas"]["ReflectionStatus"];
                        completed_the_reflection: boolean;
                    };
                };
            };
            /** @description COMMENT_REQUIRED or LEVEL_NOT_IN_COMPETENCY */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "COMMENT_REQUIRED",
                     *         "message": "You are scoring below what the student gave themselves, so a comment is required.",
                     *         "details": {
                     *           "self_level": 4,
                     *           "counter_level": 2
                     *         }
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description NOT_SUBMITTED when the reflection is a draft or already assessed, or ALREADY_SCORED by this scorer */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getReviewQueue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The worklist */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        reflection_id: string;
                        student: components["schemas"]["Person"];
                        /** Format: uuid */
                        gig_id: string | null;
                        gig_title?: string | null;
                        /** Format: uuid */
                        sprint_id?: string | null;
                        sprint_ordinal?: number | null;
                        /** Format: date-time */
                        submitted_at: string | null;
                        progress: {
                            scored_by_me: number;
                            entries: number;
                        };
                    }[];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    getRadar: {
        parameters: {
            query?: {
                gig_id?: string;
                sprint_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One axis per competency, scored or not */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "scope": {
                     *         "gig_id": null,
                     *         "sprint_id": null
                     *       },
                     *       "framework": {
                     *         "id": "aaaa1111-0000-4aaa-8aaa-aaaaaaaaaaaa",
                     *         "fw_key": "latrobe6",
                     *         "scale_min": 1,
                     *         "scale_max": 4
                     *       },
                     *       "axes": [
                     *         {
                     *           "code": "collaboration",
                     *           "short_label": "Collab.",
                     *           "position": 3,
                     *           "self": 3,
                     *           "counter": 2,
                     *           "counter_role": "supervisor"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": {
                        scope: {
                            /** Format: uuid */
                            gig_id?: string | null;
                            /** Format: uuid */
                            sprint_id?: string | null;
                        };
                        framework: {
                            /** Format: uuid */
                            id: string;
                            fw_key: string;
                            scale_min: number;
                            scale_max: number;
                        };
                        axes: {
                            code: string;
                            short_label: string | null;
                            position: number;
                            self: number | null;
                            counter: number | null;
                            counter_role: components["schemas"]["CounterRole"];
                        }[];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            /** @description Nothing written yet, so there is nothing to chart */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getProgress: {
        parameters: {
            query: {
                gig_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One series per competency */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        competencies: {
                            code: string;
                            short_label: string | null;
                            series: {
                                sprint_ordinal: number;
                                self: number | null;
                                counter: number | null;
                            }[];
                        }[];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    getCalibration: {
        parameters: {
            query?: {
                gig_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The gaps */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        competency_code: string;
                        /** Format: uuid */
                        gig_id?: string | null;
                        /** Format: uuid */
                        sprint_id?: string | null;
                        self_level: number | null;
                        counter_level: number | null;
                        counter_role: components["schemas"]["CounterRole"];
                        gap: number | null;
                    }[];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    getCoverage: {
        parameters: {
            query: {
                framework_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The gaps, in rubric order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        competency_code: string;
                        name: string;
                        short_label: string | null;
                        position: number;
                    }[];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    listExports: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exports */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Export"][];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    requestExport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description JSON only for now. The schema allows pdf and the product intends it, but rendering one needs a package the project has not adopted, so asking for it is refused rather than quietly answered with JSON.
                     * @enum {string}
                     */
                    format: "json";
                    /**
                     * Format: uuid
                     * @description Null exports the whole record.
                     */
                    reflection_id?: string | null;
                };
            };
        };
        responses: {
            /** @description Accepted, with something to poll */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Export"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    getExport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                export_id: components["parameters"]["ExportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The export */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Export"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    downloadExport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                export_id: components["parameters"]["ExportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            401: components["responses"]["Unauthenticated"];
            /** @description Not yours, still building, or the job failed */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
