#!/usr/bin/env bash
# Writes the live demo's gate (CAP-54, ADR #62): /home/ubuntu/server/
# diary-gate.caddy, imported by diary-site.caddy. Never committed: it holds the
# password hash and the cookie secret. Run ON the box, then validate and reload
# Caddy by the procedure in docs/Deployment.md.
#
#   demo-gate.sh                                 asks for the password, new secret
#   demo-gate.sh --out FILE --hash BCRYPT --secret HEX   (tests)
set -euo pipefail

out=/home/ubuntu/server/diary-gate.caddy
hash=""
secret=""
while [ $# -gt 0 ]; do
    case "$1" in
        --out) out="$2"; shift 2 ;;
        --hash) hash="$2"; shift 2 ;;
        --secret) secret="$2"; shift 2 ;;
        *) printf 'Error: unknown option %s\n' "$1" >&2; exit 1 ;;
    esac
done

if [ -z "$hash" ]; then
    read -r -s -p "Demo password: " pw
    printf '\n'
    [ ${#pw} -ge 12 ] || { printf 'Error: use at least 12 characters\n' >&2; exit 1; }
    hash="$(docker exec -i server-caddy-1 caddy hash-password --plaintext "$pw")"
fi
[ -n "$secret" ] || secret="$(openssl rand -hex 32)"
case "$secret" in
    *[!0-9a-f]*|"") printf 'Error: the secret must be lowercase hex\n' >&2; exit 1 ;;
esac

umask 027
cat > "$out" <<EOF
# Generated by scripts/demo-gate.sh. Not in git. Changing the secret signs
# everyone out; changing the hash changes the password. The username is demo.
@diary_nogate_api {
	not header Cookie *diary_gate=$secret*
	path /api/* /ai/*
}
@diary_nogate not header Cookie *diary_gate=$secret*
# route, not bare directives: inside handle, Caddy sorts header and redir
# ahead of basic_auth, which hands out the cookie without the password.
handle /gate {
	route {
		basic_auth {
			demo $hash
		}
		header Set-Cookie "diary_gate=$secret; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=604800"
		redir * / 303
	}
}
EOF
chmod 0640 "$out"
printf '==> wrote %s. The username is "demo".\n' "$out"
